# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCGApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCGApp
  pod "youtube-ios-player-helper", "~> 0.1.4"
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  target 'CCGAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CCGAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
